---
- name: Install nginx
  hosts: [web]
  tasks:
  - name: Install nginx on web servers
    become: yes
    become_user: root
    apk:
      name: nginx
      state: present


  - name: copy nginx conf
    become: yes
    become_user: root
    copy: src=nginx_server_files/nginx.conf dest=/etc/nginx/http.d/default.conf
  
  - name: Copy simple index.html
    become: yes
    become_user: root
    copy: src=nginx_server_files/index.html dest=/var/www/index.html

  - name: Restart nginx
    become: yes
    become_user: root
    service: name=nginx state=restarted enabled=yes
